- name: Deploy microservices to Kubernetes
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: "/mnt/c/Users/lika2/ansible-k8s-automation/ansible-env/bin/python"
  tasks:
    - name: Set kubeconfig path
      set_fact:
        kubeconfig_path: "{{ lookup('env', 'HOME') }}/.kube/config"

    - name: Deploy a microservice
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: "default"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "my-microservice"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: "my-microservice"
            template:
              metadata:
                labels:
                  app: "my-microservice"
              spec:
                containers:
                  - name: "my-microservice"
                    image: "my-microservice:latest"
                    imagePullPolicy: Never
                    ports:
                      - containerPort: 8080
                    command: ["python"]
                    args: ["app.py"]

    - name: Expose microservice via NodePort service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: "default"
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: my-microservice-service
          spec:
            selector:
              app: my-microservice
            ports:
              - protocol: TCP
                port: 8080
                targetPort: 8080
                nodePort: 30080
            type: NodePort

